### ISSUE TITLE
Is flutter_hooks dependency required?

### ISSUE THREAD

**Issue by davidmigloz** [santa112358/dynamic_height_grid_view#1]
Hello!

Looking at the source code, I don't see any usage of the functionality provided by `flutter_hooks`. 
Maybe is worth removing that dependency?

**Comment by 3kdeveloper** [comment]
No

**Comment by subzero911** [comment]
I am agree with topicstarter, flutter_hooks dependency seems unneeded and should be removed.
You don't need all these HookWidgets to just layout the grid.
