### ISSUE TITLE
Remove listView padding

### ISSUE THREAD

**Issue by tony123S** [santa112358/dynamic_height_grid_view#2]
Is there a way to remove the padding?

Thanks.

**Comment by santa112358** [comment]
Hi @tony123S 
Have you tried to set mainAxisSpacing and crossAxisSpacing?

**Comment by tony123S** [comment]
> mainAxisSpacing

HI, I did
```

mainAxisSpacing: 0,
crossAxisSpacing: 0,
```

**Comment by tony123S** [comment]
I managed to fix. The issue is on my code.

Thanks for this pub !
